<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="level_2_background_tile_set" tilewidth="8" tileheight="8" tilecount="2500" columns="50">
 <editorsettings>
  <export target="level_2_background_tile_set.json" format="json"/>
 </editorsettings>
 <grid orientation="orthogonal" width="16" height="16"/>
 <image source="../../gfx/tileSets/level_2/level_2_background.png" width="400" height="400"/>
 <tile id="50" type="Collision"/>
 <tile id="51" type="Collision"/>
 <tile id="52" type="Collision"/>
 <tile id="53" type="Collision"/>
 <tile id="54" type="Collision"/>
 <tile id="55" type="Collision"/>
 <tile id="56" type="Collision"/>
 <tile id="57" type="Collision"/>
 <tile id="58" type="Collision"/>
 <tile id="59" type="Collision"/>
 <tile id="60" type="Collision"/>
 <tile id="100" type="Collision"/>
 <tile id="101" type="Collision"/>
 <tile id="102" type="Collision"/>
 <tile id="103" type="Collision"/>
 <tile id="104" type="Collision"/>
 <tile id="105" type="Collision"/>
 <tile id="106" type="Collision"/>
 <tile id="107" type="Collision"/>
 <tile id="108" type="Collision"/>
 <tile id="109" type="Collision"/>
 <tile id="150" type="Collision"/>
 <tile id="151" type="Collision"/>
 <tile id="152" type="Collision"/>
 <tile id="153" type="Collision"/>
 <tile id="154" type="Collision"/>
 <tile id="155" type="Collision"/>
 <tile id="156" type="Collision"/>
 <tile id="157" type="Collision"/>
 <tile id="158" type="Collision"/>
 <tile id="159" type="Collision"/>
 <tile id="200" type="Collision"/>
 <tile id="201" type="Collision"/>
 <tile id="202" type="Collision"/>
 <tile id="203" type="Collision"/>
 <tile id="204" type="Collision"/>
 <tile id="205" type="Collision"/>
 <tile id="206" type="Collision"/>
 <tile id="207" type="Collision"/>
 <tile id="208" type="Collision"/>
 <tile id="209" type="Collision"/>
 <tile id="250" type="Collision"/>
 <tile id="251" type="Collision"/>
 <tile id="252" type="Collision"/>
 <tile id="253" type="Collision"/>
 <tile id="254" type="Collision"/>
 <tile id="255" type="Collision"/>
 <tile id="256" type="Collision"/>
 <tile id="257" type="Collision"/>
 <tile id="258" type="Collision"/>
 <tile id="259" type="Collision"/>
 <tile id="300" type="Collision"/>
 <tile id="301" type="Collision"/>
 <tile id="302" type="Collision"/>
 <tile id="303" type="Collision"/>
 <tile id="304" type="Collision"/>
 <tile id="305" type="Collision"/>
 <tile id="306" type="Collision"/>
 <tile id="307" type="Collision"/>
 <tile id="308" type="Collision"/>
 <tile id="309" type="Collision"/>
 <tile id="350" type="Collision"/>
 <tile id="351" type="Collision"/>
 <tile id="352" type="Collision"/>
 <tile id="353" type="Collision"/>
 <tile id="354" type="Collision"/>
 <tile id="355" type="Collision"/>
 <tile id="356" type="Collision"/>
 <tile id="357" type="Collision"/>
 <tile id="358" type="Collision"/>
 <tile id="359" type="Collision"/>
 <tile id="400" type="Collision"/>
 <tile id="401" type="Collision"/>
 <tile id="402" type="Collision"/>
 <tile id="403" type="Collision"/>
 <tile id="404" type="Collision"/>
 <tile id="405" type="Collision"/>
 <tile id="406" type="Collision"/>
 <tile id="407" type="Collision"/>
 <tile id="408" type="Collision"/>
 <tile id="409" type="Collision"/>
 <tile id="450" type="Collision"/>
 <tile id="451" type="Collision"/>
 <tile id="452" type="Collision"/>
 <tile id="453" type="Collision"/>
 <tile id="454" type="Collision"/>
 <tile id="455" type="Collision"/>
 <tile id="456" type="Collision"/>
 <tile id="457" type="Collision"/>
 <tile id="458" type="Collision"/>
 <tile id="459" type="Collision"/>
 <tile id="1532" type="Win"/>
 <tile id="1533" type="Win"/>
 <tile id="1534" type="Win"/>
 <tile id="1535" type="Win"/>
 <tile id="1582" type="Win"/>
 <tile id="1583" type="Win"/>
 <tile id="1584" type="Win"/>
 <tile id="1585" type="Win"/>
 <tile id="1632" type="Win"/>
 <tile id="1633" type="Win"/>
 <tile id="1634" type="Win"/>
 <tile id="1635" type="Win"/>
 <tile id="1682" type="Win"/>
 <tile id="1683" type="Win"/>
 <tile id="1684" type="Win"/>
 <tile id="1685" type="Win"/>
 <tile id="1862" type="Kill"/>
 <tile id="1863" type="Kill"/>
 <tile id="1864" type="Kill"/>
 <tile id="1865" type="Kill"/>
 <tile id="1866" type="Kill"/>
 <tile id="1867" type="Kill"/>
 <tile id="1868" type="Kill"/>
 <tile id="1869" type="Kill"/>
 <tile id="1912" type="Kill"/>
 <tile id="1913" type="Kill"/>
 <tile id="1914" type="Kill"/>
 <tile id="1915" type="Kill"/>
 <tile id="1916" type="Kill"/>
 <tile id="1917" type="Kill"/>
 <tile id="1918" type="Kill"/>
 <tile id="1919" type="Kill"/>
 <tile id="1962" type="Kill"/>
 <tile id="1963" type="Kill"/>
 <tile id="1964" type="Kill"/>
 <tile id="1965" type="Kill"/>
 <tile id="1966" type="Kill"/>
 <tile id="1967" type="Kill"/>
 <tile id="1968" type="Kill"/>
 <tile id="1969" type="Kill"/>
 <tile id="2012" type="Kill"/>
 <tile id="2013" type="Kill"/>
 <tile id="2014" type="Kill"/>
 <tile id="2015" type="Kill"/>
 <tile id="2016" type="Kill"/>
 <tile id="2017" type="Kill"/>
 <tile id="2018" type="Kill"/>
 <tile id="2019" type="Kill"/>
 <tile id="2062" type="Kill"/>
 <tile id="2063" type="Kill"/>
 <tile id="2064" type="Kill"/>
 <tile id="2065" type="Kill"/>
 <tile id="2066" type="Kill"/>
 <tile id="2067" type="Kill"/>
 <tile id="2068" type="Kill"/>
 <tile id="2069" type="Kill"/>
</tileset>
